### ISSUE TITLE
Limit workflow runs on push

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-react-app-playground#80]
### Issue description
> **ESTIMATE** TBD

Right now each PR requires 2 full workflow runs, one for the push and one for the pull request. Almost all pull requests are from a ticket branch, which we never look at on react-app-dev. Additionally multiple jobs running at the same time will impact performance. So we should follow what we did for the cgov-digital-platform and only do builds for:
```
on:
  push:
    branches:
      - master
      - main
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
      - 'prototype/**'
    tags:
      - '*'
  pull_request:
```
(Yes, `pull_request:` has nothing under it.)

For only the playground we will also add `workflow_call:` to the list of triggers.
